### ISSUE TITLE
Test steps shift VSCode's test runner icons

### ISSUE THREAD

**Issue by jondam93** [vitalets/playwright-magic-steps#7]
For every `// step:` added to my code, it shifts the icon for the test runner one line down. See icons in left hand margin:

![Image](https://github.com/user-attachments/assets/5ae053b7-5780-4c2d-ba42-3b99cf7fbab2)

Is this a known issue?

**Comment by vitalets** [comment]
I assume there can be such situation, but I can't reproduce it. Could you share the steps how you get it?
When I simply add more steps, runner icons shift correctly:

<img width="674" alt="Image" src="https://github.com/user-attachments/assets/58271d83-ddd1-407d-abda-3550e3ff673d" />

**Comment by vitalets** [comment]
While checking this issue, I've realized that there is no configuration setup for VS Code extension is readme. 
I've updated the readme. Could you try to add the following lines to `.vscode/settings.json`:
```json
"playwright.env": {
  "NODE_OPTIONS": "-r playwright-magic-steps"
},
```

**Comment by jondam93** [comment]
I already had the configuration added to `settings.json` at the time of posting, so that unfortunately doesn't fix anything.
It's hard to pinpoint exactly what steps I've made in order to get this bug, as I just added the magic steps to an existing project.
When I try to reproduce the bug in a fresh setup, I am also unable to do so.

**Comment by jondam93** [comment]
Actually, upon removing the configuration from `.vscode/settings.json`, the icons are once again placed where they should be:

![Image](https://github.com/user-attachments/assets/fedb2926-a2b5-4ef5-b548-946eae5c57a8)

![Image](https://github.com/user-attachments/assets/e7120945-b057-452f-addd-80b85efc6912)

**Comment by jondam93** [comment]
It was a good old fashioned PEBKAC after all 😅 I had used the installation steps for CJS instead of ESM. When changing `.vscode/settings.json` like this, everything works as expected:

![Image](https://github.com/user-attachments/assets/0a85ae75-d69e-4f37-b9d3-2c9348252172)

![Image](https://github.com/user-attachments/assets/9ba80aca-fbb5-468a-9c37-2e7cee44e122)

**Comment by jondam93** [comment]
I've found something that has made me if possible even more confused. It seems the file itself is affected, rather than the code. 

See examples below, where two files with different names have the exact same code. However, `example.spec.ts` behaves as expected, while `dashboard.spec.ts` has the described issue:

![Image](https://github.com/user-attachments/assets/9a97130e-f403-4c76-9f83-eea435e2a717)

The files are right next to each other in the `/tests` directory

**Comment by jondam93** [comment]
I posted a question to StackOverflow with detailed steps on how to reproduce:
https://stackoverflow.com/questions/79414236/why-are-my-test-runner-icons-on-the-wrong-line-only-in-certain-files

**Comment by vitalets** [comment]
@jondam93 

Could you please try two scenarios:

1. When you face that issue, restart VS code extensions -> doesn't it help?

And another one:

2. When you face that issue, run `npx playwright clear-cache` to clear Playwright cache with transpiled files.

**Comment by jondam93** [comment]
Tried both with no success, unfortunately.
I've also tried disabling all extensions in order to see if it's an issue there, but as soon as I enable the Playwright extension the icons shift.

**Comment by vitalets** [comment]
Hmm, ok, thank you! In the situation when `example.spec.ts` has correct icons, but `dashboard.spec.ts` does not -> what if you rename `dashboard.spec.ts` to let's say `dashboard123.spec.ts`?

**Comment by jondam93** [comment]
I've tried renaming it to a lot of different names, including `example.spec.ts`, but unfortunately the icons remain wrong

**Comment by vitalets** [comment]
And when you comment these line, icons go to correct place even without re-running tests?

![Image](https://github.com/user-attachments/assets/de699f42-225d-4182-b3ac-e9c4fe4a68e1)

**Comment by jondam93** [comment]
Yes, when commenting out the lines the test runner refreshes and the icons reappear at the correct place

**Comment by vitalets** [comment]
I'll check Playwright vscode extension [sources](https://github.com/microsoft/playwright-vscode/tree/main), maybe it can help.
In general the problem is following: during compilation steps add extra line for closing `});` of the step function. That's why line offset can shift.
